version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: coc-donations:dev
    command: ["npm install --include=dev && npm start"]
    init: true
    volumes:
      - type: bind
        source: .
        target: /app
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: coc-donations:latest
    ports:
      - "80:80"
    env_file:
      - .env
