name: Apply Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/environments/dev

    if: github.actor == 'jburns24'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: alexellis/arkade-get@master
        with:
          # vault: latest
          # jq: latest
          terraform: latest
          terragrunt: latest

      - name: Terragrunt apply
        run: |
          terragrunt apply --terragrunt-non-interactive -auto-approve
        env:
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: "true"
          TF_VAR_discord_token: ${{ secrets.DISCORD_TOKEN }}
          TF_VAR_clash_token: ${{ secrets.CLASH_TOKEN_MULTI_IP }}
          TF_VAR_image_name: "${{ github.repository }}:${{ github.sha }}"
