name: Apply Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'infra/**'

env:
  # Setting an environment variable with the value of a configuration variable
#   APP_NAME: ${{ vars.APP_NAME }}
#   ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#   ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#   ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET}}
#   ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  TF_VAR_discord_token: ${{ secrets.DISCORD_TOKEN }}
  TF_VAR_clash_token: ${{ secrets.CLASH_TOKEN }}

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra/environments/dev

    if: github.actor == 'jburns24'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: alexellis/arkade-get@master
        with:
          # vault: latest
          # jq: latest
          terraform: latest
          terragrunt: latest

      - name: Terragrunt apply
        run: terragrunt apply --terragrunt-non-interactive -auto-approve
