name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/master'

    steps:
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'node-rnc'
          images: 'ghcr.io/jburns24/discord-coc-donations-ws-app:${{ github.sha }}'
