name: Delete Workflow

on:
  workflow_dispatch:
jobs:
  delete:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infra

    if: github.actor == 'jburns24'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: alexellis/arkade-get@master
        with:
          # vault: latest
          # jq: latest
          terraform: latest
          terragrunt: latest

      - name: Terragrunt hcl check
        run: terragrunt hclfmt --terragrunt-check

      - name: Terraform fmt check
        run: terraform fmt -check -recursive

      - name: Terragrunt validate check
        run: terragrunt run-all validate --terragrunt-non-interactive

      - name: Terragrunt Plan
        id: terragrunt_plan
        run: |
          terragrunt plan --terragrunt-non-interactive -out plan.out
          terragrunt show --terragrunt-non-interactive -no-color -json plan.out > plan.json
        continue-on-error: true # Continue on error to ensure the plan is added as a comment on the PR.

      - uses: liatrio/terraform-change-pr-commenter@v1.3.2
        with:
          json-file: ./plan.json

      - name: Status
        if: contains(steps.*.outcome, 'failure')
        run: exit 1
